#### Find the relationship between userID and other users based on their rated object (e.g. placeID)
#### The algorithm looks for the common rated placeID between userID and other users and compute the correlation between the rating parameters (rating, food_rating, service_rating) on these rated placeID and return the most highest r-result (Pearson correlation). 
#### The final highest r-result will show that who are the closest (neighbors) with the userID

In [1]:
from Starts.startml import *
from Starts.startvis import *
from Starts.startmodrec import *
%matplotlib inline
rcParams['figure.figsize'] = 20, 6

local_kwargs {'data_path_1': '9_RECS/rating_final.csv', 'data_path_2': '9_RECS/chefmozcuisine.csv', 'data_path_3': '', 'drop_obj_col': False, 'nan_drop_col': False, 'nan_drop_row': False, 'nan_zero': False, 'nan_mean': True, 'nan_mean_neighbors': False}

In [2]:
rating_final = train_data
rating_final.head()

  userID  placeID  rating  food_rating  service_rating
0  U1077   135085       2            2               2
1  U1077   135038       2            2               1
2  U1077   132825       2            2               2
3  U1077   135060       1            2               2
4  U1068   135104       1            1               2

In [3]:
len(rating_final['userID'].unique()), rating_final['userID'].unique()[0], rating_final['userID'].unique()[1]

(138, 'U1077', 'U1068')

In [4]:
rating_final[rating_final['userID']=='U1077']

    userID  placeID  rating  food_rating  service_rating
0    U1077   135085       2            2               2
1    U1077   135038       2            2               1
2    U1077   132825       2            2               2
3    U1077   135060       1            2               2
433  U1077   135027       0            1               1

In [5]:
rating_final[rating_final['userID']=='U1068']

     userID  placeID  rating  food_rating  service_rating
4     U1068   135104       1            1               2
5     U1068   132740       0            0               0
6     U1068   132663       1            1               1
7     U1068   132732       0            0               0
8     U1068   132630       1            1               1
1158  U1068   132733       1            1               0
1159  U1068   132594       1            1               1
1160  U1068   132660       0            0               0

In [6]:
correl = StartModREC.find_nearest_neighbors_by_correlation(data=rating_final, user_id='userID', rating_id='placeID', 
                                                           user_key='U1077')

U1077 {0: 135085, 1: 135038, 2: 132825, 3: 135060, 433: 135027}
rating {0: 2, 1: 2, 2: 2, 3: 1, 433: 0}
food_rating {0: 2, 1: 2, 2: 2, 3: 2, 433: 1}
service_rating {0: 2, 1: 1, 2: 2, 3: 2, 433: 1}


U1108 [(68, 135085)]
U1108 rating_list:  [1, 2, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1108
0      2      1
1      2      2
2      2      1
numerator  0.0
denominator  0.0
0


U1055 [(182, 132825)]
U1055 rating_list:  [2, 2, 2]
U1077 rating_user:  [2, 2, 2]
   U1077  U1055
0      2      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1053 [(185, 132825), (195, 135038), (196, 135060)]
U1053 rating_list:  [2, 2, 1]
U1077 rating_user:  [1, 2, 2]
   U1077  U1053
0      1      2
1      2      2
2      2      1
numerator  -0.333333333333
denominator  0.666666666667
-0.5


U1064 [(206, 135060)]
U1064 rating_list:  [1, 0, 1]
U1077 rating_user:  [1, 2, 2]
   U1077  U1064
0      1      1
1      2      0
2      2      1
numerator  -0.333333333333
denominator  0.666666666667
-0.5


U1081 [(208, 132825), (211, 135085), (214, 135027)]
U1081 rating_list:  [0, 1, 1]
U1077 rating_user:  [0, 1, 1]
   U1077  U1081
0      0      0
1      1      1
2      1      1
numerator  0.666666666667
denominator  0.666666666667
1.0


U1001 [(216, 132825), (688, 135085)]
U1001 rating_list:  [0, 1, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1001
0      2      0
1      2      1
2      2      1
numerator  0.0
denominator  0.0
0


U1056 [(245, 135027), (246, 135085), (248, 132825)]
U1056 rating_list:  [2, 2, 2]
U1077 rating_user:  [2, 2, 2]
   U1077  U1056
0      2      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1134 [(253, 132825), (257, 135085)]
U1134 rating_list:  [2, 1, 2]
U1077 rating_user:  [2, 2, 2]
   U1077  U1134
0      2      2
1      2      1
2      2      2
numerator  0.0
denominator  0.0
0


U1106 [(530, 135085)]
U1106 rating_list:  [2, 2, 2]
U1077 rating_user:  [2, 2, 2]
   U1077  U1106
0      2      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1126 [(276, 135038)]
U1126 rating_list:  [1, 0, 1]
U1077 rating_user:  [2, 2, 1]
   U1077  U1126
0      2      1
1      2      0
2      1      1
numerator  -0.333333333333
denominator  0.666666666667
-0.5


U1125 [(306, 135060), (307, 135038)]
U1125 rating_list:  [2, 2, 1]
U1077 rating_user:  [2, 2, 1]
   U1077  U1125
0      2      2
1      2      2
2      1      1
numerator  0.666666666667
denominator  0.666666666667
1.0


U1076 [(318, 135038), (319, 135027)]
U1076 rating_list:  [0, 1, 1]
U1077 rating_user:  [0, 1, 1]
   U1077  U1076
0      0      0
1      1      1
2      1      1
numerator  0.666666666667
denominator  0.666666666667
1.0


U1022 [(327, 135060), (329, 135038)]
U1022 rating_list:  [2, 1, 2]
U1077 rating_user:  [2, 2, 1]
   U1077  U1022
0      2      2
1      2      1
2      1      2
numerator  -0.333333333333
denominator  0.666666666667
-0.5


U1116 [(345, 135060), (346, 135038), (347, 135085), (351, 135027), (352, 132825)]
U1116 rating_list:  [2, 2, 2]
U1077 rating_user:  [2, 2, 2]
   U1077  U1116
0      2      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1007 [(592, 135085), (600, 135038)]
U1007 rating_list:  [1, 1, 0]
U1077 rating_user:  [2, 2, 1]
   U1077  U1007
0      2      1
1      2      1
2      1      0
numerator  0.666666666667
denominator  0.666666666667
1.0


U1024 [(389, 132825), (390, 135060), (394, 135027), (398, 135038)]
U1024 rating_list:  [1, 1, 0]
U1077 rating_user:  [2, 2, 1]
   U1077  U1024
0      2      1
1      2      1
2      1      0
numerator  0.666666666667
denominator  0.666666666667
1.0


U1132 [(401, 135038), (402, 132825), (403, 135085), (410, 135027)]
U1132 rating_list:  [2, 1, 0]
U1077 rating_user:  [0, 1, 1]
   U1077  U1132
0      0      2
1      1      1
2      1      0
numerator  -1.0
denominator  1.15470053838
-0.866025403784


U1120 [(420, 135085), (424, 135038)]
U1120 rating_list:  [0, 0, 0]
U1077 rating_user:  [2, 2, 1]
   U1077  U1120
0      2      0
1      2      0
2      1      0
numerator  0.0
denominator  0.0
0


U1004 [(425, 135060)]
U1004 rating_list:  [1, 1, 1]
U1077 rating_user:  [1, 2, 2]
   U1077  U1004
0      1      1
1      2      1
2      2      1
numerator  0.0
denominator  0.0
0


U1036 [(450, 135085), (452, 132825)]
U1036 rating_list:  [2, 2, 2]
U1077 rating_user:  [2, 2, 2]
   U1077  U1036
0      2      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1071 [(466, 135060), (468, 132825)]
U1071 rating_list:  [2, 2, 2]
U1077 rating_user:  [2, 2, 2]
   U1077  U1071
0      2      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1114 [(896, 132825)]
U1114 rating_list:  [0, 0, 0]
U1077 rating_user:  [2, 2, 2]
   U1077  U1114
0      2      0
1      2      0
2      2      0
numerator  0.0
denominator  0.0
0


U1084 [(485, 135085)]
U1084 rating_list:  [2, 2, 2]
U1077 rating_user:  [2, 2, 2]
   U1077  U1084
0      2      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1049 [(487, 132825), (1050, 135085)]
U1049 rating_list:  [0, 0, 0]
U1077 rating_user:  [2, 2, 2]
   U1077  U1049
0      2      0
1      2      0
2      2      0
numerator  0.0
denominator  0.0
0


U1019 [(491, 135038)]
U1019 rating_list:  [0, 0, 0]
U1077 rating_user:  [2, 2, 1]
   U1077  U1019
0      2      0
1      2      0
2      1      0
numerator  0.0
denominator  0.0
0


U1113 [(502, 135038), (504, 135085)]
U1113 rating_list:  [1, 2, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1113
0      2      1
1      2      2
2      2      1
numerator  0.0
denominator  0.0
0


U1104 [(511, 132825), (512, 135085)]
U1104 rating_list:  [2, 2, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1104
0      2      2
1      2      2
2      2      1
numerator  0.0
denominator  0.0
0


U1045 [(544, 132825), (547, 135085), (551, 135060)]
U1045 rating_list:  [2, 2, 2]
U1077 rating_user:  [1, 2, 2]
   U1077  U1045
0      1      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1009 [(556, 135060), (560, 135038), (561, 132825)]
U1009 rating_list:  [1, 1, 0]
U1077 rating_user:  [2, 2, 2]
   U1077  U1009
0      2      1
1      2      1
2      2      0
numerator  0.0
denominator  0.0
0


U1016 [(571, 135060), (573, 135085)]
U1016 rating_list:  [2, 2, 0]
U1077 rating_user:  [2, 2, 2]
   U1077  U1016
0      2      2
1      2      2
2      2      0
numerator  0.0
denominator  0.0
0


U1078 [(763, 135060)]
U1078 rating_list:  [2, 2, 2]
U1077 rating_user:  [1, 2, 2]
   U1077  U1078
0      1      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1099 [(616, 135038), (617, 135060)]
U1099 rating_list:  [2, 2, 2]
U1077 rating_user:  [1, 2, 2]
   U1077  U1099
0      1      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1013 [(639, 135085), (1111, 135060)]
U1013 rating_list:  [1, 1, 0]
U1077 rating_user:  [1, 2, 2]
   U1077  U1013
0      1      1
1      2      1
2      2      0
numerator  -0.333333333333
denominator  0.666666666667
-0.5


U1054 [(642, 135060), (649, 135038)]
U1054 rating_list:  [2, 1, 1]
U1077 rating_user:  [2, 2, 1]
   U1077  U1054
0      2      2
1      2      1
2      1      1
numerator  0.333333333333
denominator  0.666666666667
0.5


U1128 [(1010, 135060)]
U1128 rating_list:  [0, 0, 0]
U1077 rating_user:  [1, 2, 2]
   U1077  U1128
0      1      0
1      2      0
2      2      0
numerator  0.0
denominator  0.0
0


U1062 [(726, 135085), (729, 132825), (735, 135038)]
U1062 rating_list:  [0, 0, 0]
U1077 rating_user:  [2, 2, 1]
   U1077  U1062
0      2      0
1      2      0
2      1      0
numerator  0.0
denominator  0.0
0


U1101 [(679, 135027), (684, 135038)]
U1101 rating_list:  [2, 2, 1]
U1077 rating_user:  [2, 2, 1]
   U1077  U1101
0      2      2
1      2      2
2      1      1
numerator  0.666666666667
denominator  0.666666666667
1.0


U1135 [(695, 135085), (705, 132825), (718, 135060)]
U1135 rating_list:  [0, 0, 0]
U1077 rating_user:  [1, 2, 2]
   U1077  U1135
0      1      0
1      2      0
2      2      0
numerator  0.0
denominator  0.0
0


U1032 [(702, 135085), (707, 135038), (709, 135060)]
U1032 rating_list:  [1, 1, 1]
U1077 rating_user:  [1, 2, 2]
   U1077  U1032
0      1      1
1      2      1
2      2      1
numerator  0.0
denominator  0.0
0


U1092 [(730, 135085)]
U1092 rating_list:  [0, 0, 0]
U1077 rating_user:  [2, 2, 2]
   U1077  U1092
0      2      0
1      2      0
2      2      0
numerator  0.0
denominator  0.0
0


U1085 [(755, 132825)]
U1085 rating_list:  [2, 2, 2]
U1077 rating_user:  [2, 2, 2]
   U1077  U1085
0      2      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1109 [(751, 132825), (759, 135085), (760, 135038)]
U1109 rating_list:  [2, 2, 2]
U1077 rating_user:  [2, 2, 1]
   U1077  U1109
0      2      2
1      2      2
2      1      2
numerator  0.0
denominator  0.0
0


U1098 [(771, 135060), (790, 135085), (791, 132825), (794, 135038)]
U1098 rating_list:  [1, 1, 1]
U1077 rating_user:  [2, 2, 1]
   U1077  U1098
0      2      1
1      2      1
2      1      1
numerator  0.0
denominator  0.0
0


U1046 [(922, 135085)]
U1046 rating_list:  [1, 2, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1046
0      2      1
1      2      2
2      2      1
numerator  0.0
denominator  0.0
0


U1122 [(781, 135038), (782, 135085)]
U1122 rating_list:  [2, 2, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1122
0      2      2
1      2      2
2      2      1
numerator  0.0
denominator  0.0
0


U1033 [(804, 135085), (811, 135038)]
U1033 rating_list:  [1, 1, 1]
U1077 rating_user:  [2, 2, 1]
   U1077  U1033
0      2      1
1      2      1
2      1      1
numerator  0.0
denominator  0.0
0


U1089 [(825, 135085), (831, 135038)]
U1089 rating_list:  [0, 0, 0]
U1077 rating_user:  [2, 2, 1]
   U1077  U1089
0      2      0
1      2      0
2      1      0
numerator  0.0
denominator  0.0
0


U1003 [(819, 132825)]
U1003 rating_list:  [2, 2, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1003
0      2      2
1      2      2
2      2      1
numerator  0.0
denominator  0.0
0


U1091 [(833, 132825)]
U1091 rating_list:  [0, 1, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1091
0      2      0
1      2      1
2      2      1
numerator  0.0
denominator  0.0
0


U1027 [(855, 135085)]
U1027 rating_list:  [1, 1, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1027
0      2      1
1      2      1
2      2      1
numerator  0.0
denominator  0.0
0


U1029 [(861, 135085), (864, 132825)]
U1029 rating_list:  [1, 1, 0]
U1077 rating_user:  [2, 2, 2]
   U1077  U1029
0      2      1
1      2      1
2      2      0
numerator  0.0
denominator  0.0
0


U1086 [(870, 135085), (875, 135060)]
U1086 rating_list:  [1, 1, 1]
U1077 rating_user:  [1, 2, 2]
   U1077  U1086
0      1      1
1      2      1
2      2      1
numerator  0.0
denominator  0.0
0


U1137 [(882, 135085), (889, 132825)]
U1137 rating_list:  [2, 2, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1137
0      2      2
1      2      2
2      2      1
numerator  0.0
denominator  0.0
0


U1090 [(964, 135085)]
U1090 rating_list:  [2, 2, 2]
U1077 rating_user:  [2, 2, 2]
   U1077  U1090
0      2      2
1      2      2
2      2      2
numerator  0.0
denominator  0.0
0


U1061 [(906, 132825)]
U1061 rating_list:  [1, 2, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1061
0      2      1
1      2      2
2      2      1
numerator  0.0
denominator  0.0
0


U1059 [(999, 135085), (1002, 132825)]
U1059 rating_list:  [2, 1, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1059
0      2      2
1      2      1
2      2      1
numerator  0.0
denominator  0.0
0


U1057 [(970, 132825)]
U1057 rating_list:  [1, 1, 0]
U1077 rating_user:  [2, 2, 2]
   U1077  U1057
0      2      1
1      2      1
2      2      0
numerator  0.0
denominator  0.0
0


U1025 [(985, 132825)]
U1025 rating_list:  [0, 0, 0]
U1077 rating_user:  [2, 2, 2]
   U1077  U1025
0      2      0
1      2      0
2      2      0
numerator  0.0
denominator  0.0
0


U1006 [(1025, 132825)]
U1006 rating_list:  [1, 1, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1006
0      2      1
1      2      1
2      2      1
numerator  0.0
denominator  0.0
0

U1073 [(1043, 135060)]
U1073 rating_list:  [0, 0, 0]
U1077 rating_user:  [1, 2, 2]
   U1077  U1073
0      1      0
1      2      0
2      2      0
numerator  0.0
denominator  0.0
0


U1002 [(1064, 132825), (1071, 135085)]
U1002 rating_list:  [1, 1, 1]
U1077 rating_user:  [2, 2, 2]
   U1077  U1002
0      2      1
1      2      1
2      2      1
numerator  0.0
denominator  0.0
0

In [7]:
correl

[('U1108', 0),
 ('U1055', 0),
 ('U1053', -0.50000000000000133),
 ('U1064', -0.50000000000000044),
 ('U1081', 1.0000000000000002),
 ('U1001', 0),
 ('U1056', 0),
 ('U1134', 0),
 ('U1106', 0),
 ('U1126', -0.50000000000000044),
 ('U1125', 1.0),
 ('U1076', 1.0000000000000002),
 ('U1022', -0.50000000000000133),
 ('U1116', 0),
 ('U1007', 1.0000000000000002),
 ('U1024', 1.0000000000000002),
 ('U1132', -0.86602540378443849),
 ('U1120', 0),
 ('U1004', 0),
 ('U1036', 0),
 ('U1071', 0),
 ('U1114', 0),
 ('U1084', 0),
 ('U1049', 0),
 ('U1019', 0),
 ('U1113', 0),
 ('U1104', 0),
 ('U1045', 0),
 ('U1009', 0),
 ('U1016', 0),
 ('U1078', 0),
 ('U1099', 0),
 ('U1013', -0.50000000000000044),
 ('U1054', 0.49999999999999956),
 ('U1128', 0),
 ('U1062', 0),
 ('U1101', 1.0),
 ('U1135', 0),
 ('U1032', 0),
 ('U1092', 0),
 ('U1085', 0),
 ('U1109', 0),
 ('U1098', 0),
 ('U1046', 0),
 ('U1122', 0),
 ('U1033', 0),
 ('U1089', 0),
 ('U1003', 0),
 ('U1091', 0),
 ('U1027', 0),
 ('U1029', 0),
 ('U1086', 0),
 ('U1137', 0),
 ('U1090', 0),
 ('U1061', 0),
 ('U1059', 0),
 ('U1057', 0),
 ('U1025', 0),
 ('U1006', 0),
 ('U1073', 0),
 ('U1002', 0)]

In [8]:
StartML.findMaxMinValueDict(dict(correl))

{'U1007': 1.0000000000000002,
 'U1024': 1.0000000000000002,
 'U1076': 1.0000000000000002,
 'U1081': 1.0000000000000002}

#### Conclusion: we choose the max result in correl_list to see that users with IDs U1007, U1024, U1076, U1081 
#### are the closest neighbors with userID U1077.